#!/usr/bin/perl 
# 
# wrapper to gatk to make things a bit more simple
# 
# 
# Kim Brugger (13 Jul 2010), contact: kim.brugger@easih.ac.uk

use strict;
use warnings;
use Data::Dumper;

my $argv_list = "";

my $java = "/usr/local/Cluster-Apps/java/jdk1.6.0_18/bin/java";
my $gatk = "/home/kb468/bin/gatk_live/GenomeAnalysisTK.jar";
#my $gatk = "/home/kb468/bin/GATK/GenomeAnalysisTK.jar";

#my $resources  = " -resources ~/src/gatk/Sting/R/  -Rscript /usr/bin/Rscript ";
my $resources  = " -resources ~/bin/gatk_live/resources/R  -Rscript /usr/bin/Rscript ";



foreach my $argv ( @ARGV ) {
  next if ( $argv eq $0);

  
  if ( $argv =~ / /) {
    $argv_list .= qq{ "$argv" };
  }
  else {
    $argv_list .= qq{ $argv };
  }

  $argv_list .=  $resources if ( $argv eq "GenerateVariantClusters" || $argv eq "VariantRecalibrator" );

}

#print "$java -jar $gatk $argv_list\n";
system "$java -jar $gatk $argv_list\n";
my $exit_value = $?>>8;
exit $exit_value;










__END__


#!/bin/bash


i=0
argv=()
for arg in "$@"; do
    if [[ $arg =~ .*\ .* ]]
    then
      argv[$i]="\"$arg\"";
    else
      argv[$i]="$arg";
    fi
    i=$((i + 1))
done

echo "/usr/local/java/jre1.6.0_19/bin/java -jar /usr/local/installed/GATK/java/GenomeAnalysisTK.jar ${argv[@]} "

/usr/local/java/jre1.6.0_19/bin/java -jar /usr/local/installed/GATK/java/GenomeAnalysisTK.jar "${argv[@]}"

