#!/bin/bash
#
# Checks for group writeable permissions in the /data directories. If wrong permissions they are fixed
# 
# 
# Kim Brugger (15 Jun 2011), contact: kim.brugger@easih.ac.uk

for basedir in `ls /data/`
do

 if [[ "$basedir" =~ [A-Z]$ ]]; then
    for range in `ls /data/$basedir/`
    do
    
    if [[ "$range" =~ [0-9]_[0-9] ]]; then
#        echo "Looking in: /data/$basedir/$range/";

        for project in `ls /data/$basedir/$range/`
        do
	    chmod -R 4775 /data/$basedir/$range/$project
	done
    fi
    done
 fi
done


